package com.xiaoxuhui.gamehub

import java.io.File
import java.io.FileOutputStream
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.nio.charset.CodingErrorAction
import java.security.MessageDigest
import java.util.zip.CRC32

/** Protocol v1 uses stored, UTF8, regular-file ZIPs generated by resource-bundle.mjs. */
internal object ResourceArchive {
    private data class Entry(val path: String, val offset: Int, val dataOffset: Int, val size: Int, val crc: Long, val time: Int, val date: Int)
    fun extract(archive: File, destination: File, game: ResourceGame, cancelled: () -> Boolean = { false }) {
        require(archive.length() == game.archiveBytes && archive.length() <= ResourcePolicy.MAX_ARCHIVE)
        val bytes = archive.inputStream().use { ResourceIo.readBounded(it, game.archiveBytes) }; require(bytes.size.toLong() == game.archiveBytes && ResourcePolicy.sha256(bytes) == game.archiveSha256) { "Resource ZIP digest mismatch" }
        val buffer = ByteBuffer.wrap(bytes).order(ByteOrder.LITTLE_ENDIAN)
        fun u16(at: Int) = buffer.getShort(at).toInt() and 65535
        fun u32(at: Int) = buffer.getInt(at).toLong() and 0xffffffffL
        fun has(at: Int, count: Int) { require(at >= 0 && count >= 0 && at.toLong() + count <= bytes.size) { "Truncated resource ZIP" } }
        fun name(at: Int, size: Int): String { has(at, size); return Charsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(bytes, at, size)).toString() }
        val expected = game.files.associateBy { it.path }; val entries = ArrayList<Entry>(); val names = HashSet<String>(); var at = 0; var total = 0L
        while (at + 4 <= bytes.size && u32(at) == 0x04034b50L) {
            require(!cancelled()) { "Resource install cancelled" }; has(at, 30)
            require(u16(at + 4) <= 20 && u16(at + 6) == 0x800 && u16(at + 8) == 0 && u16(at + 28) == 0) { "Unsupported ZIP flags, compression or extra fields" }
            val size = u32(at + 18); require(size == u32(at + 22) && size <= ResourcePolicy.MAX_FILE)
            val nameBytes = u16(at + 26); val path = ResourcePolicy.safePath(name(at + 30, nameBytes)); require(names.add(path.lowercase(java.util.Locale.ROOT)))
            val file = expected[path] ?: error("Unregistered ZIP file"); require(file.bytes == size)
            val start = at + 30 + nameBytes; has(start, size.toInt()); total += size; require(total <= ResourcePolicy.MAX_UNPACKED && entries.size < 2000)
            val crc = CRC32().apply { update(bytes, start, size.toInt()) }.value; require(crc == u32(at + 14)) { "ZIP CRC mismatch" }
            val hash = MessageDigest.getInstance("SHA-256").run { update(bytes, start, size.toInt()); digest().joinToString("") { "%02x".format(it) } }; require(hash == file.sha256)
            entries.add(Entry(path, at, start, size.toInt(), crc, u16(at + 10), u16(at + 12))); at = start + size.toInt()
        }
        require(entries.size == expected.size && entries.map { it.path }.toSet() == expected.keys) { "Missing ZIP file" }
        val centralStart = at
        for (entry in entries) {
            has(at, 46); require(u32(at) == 0x02014b50L && u16(at + 4) <= 20 && u16(at + 6) <= 20 && u16(at + 8) == 0x800 && u16(at + 10) == 0)
            require(u16(at + 12) == entry.time && u16(at + 14) == entry.date && u32(at + 16) == entry.crc && u32(at + 20) == entry.size.toLong() && u32(at + 24) == entry.size.toLong())
            require(u16(at + 30) == 0 && u16(at + 32) == 0 && u16(at + 34) == 0 && u16(at + 36) == 0 && u32(at + 38) == 0L && u32(at + 42) == entry.offset.toLong()) { "ZIP links or special attributes rejected" }
            val nameBytes = u16(at + 28); require(name(at + 46, nameBytes) == entry.path); at += 46 + nameBytes
        }
        val centralSize = at - centralStart; has(at, 22)
        require(u32(at) == 0x06054b50L && u16(at + 4) == 0 && u16(at + 6) == 0 && u16(at + 8) == entries.size && u16(at + 10) == entries.size && u32(at + 12) == centralSize.toLong() && u32(at + 16) == centralStart.toLong() && u16(at + 20) == 0 && at + 22 == bytes.size) { "Invalid ZIP end record" }
        require(destination.isDirectory || destination.mkdirs())
        val root = destination.canonicalFile
        for (entry in entries) {
            require(!cancelled()) { "Resource install cancelled" }
            val output = File(root, entry.path); require(output.canonicalPath.startsWith(root.path + File.separator) && output.canonicalFile == output.absoluteFile)
            require(output.parentFile!!.isDirectory || output.parentFile!!.mkdirs())
            FileOutputStream(output).use { stream -> stream.write(bytes, entry.dataOffset, entry.size); stream.fd.sync() }
        }
    }
}
